apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localshop-platform
  namespace: argocd
spec:
  project: localshop
  source:
    repoURL: 'https://github.com/HimanshuVK1/e-commers-webapp-localshop.git'
    path: platform
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
